stages:
  - deploy

pages:
  stage: deploy
  image: alpine:3.20
  tags:
    - gong
  script:
    - rm -rf public
    - mkdir public
    - cp -R docs/. public/
  artifacts:
    paths:
      - public
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
